name: Conformance test harness

on:
  schedule:
    - cron: '23 5 * * *'

jobs:
  conformance:
    strategy:
      fail-fast: false
      matrix:
        branch:
          - 'main'
          - 'versions/6.0.0'
    uses: ./.github/workflows/cth-test.yml
    with:
      branch: ${{ matrix.branch }}
